### PR TITLE
tagFilter argv and updated apidoc-core dependency

### PR DESCRIPTION
**Pull request by OLRG**
TagFilter argv support for getting endpoints that marked with specified tags.

### CODE REVIEW

**Comment by rottmann** [comment]
Added apiPrivate in the last release.
Set your Pull as proposal, have to watch if apiPrivate is enough to solve the problem for the most users.
[#54](https://github.com/apidoc/apidoc-core/pull/54)

**Comment by OLRG** [comment]
Yes, I have seen apiPrivate but it is not actually the same as apiTagFilter because it does not gives flexibility to choose  which endpoints should be in the output(I mean without changing a file).

**Comment by popenkomaksim** [comment]
As far as I can see, main idea is to filter endpoints during build process. 

For example:
We have bunch of endpoints: endpoint1, endpoint2, endpoint3, endpoint4.
We need ability to have different builds:
– first should contains all of them;
– second should contains endpoint1, endpoint2;
– third should contains endpoint1, endpoint3.

So main idea is to tag endpoints by some criteria.
endpoint1 @apiTagFilter for-second-build for-third-build
endpoint2 @apiTagFilter for-second-build
endpoint3 @apiTagFilter for-third-build
endpoint4  @apiTagFilter // by default if empty will be omitted during filtering.

**Comment by NicolasCARPi** [comment]
Let's assume apiPrivate is good enough for now.

**Pull request closed without merging**
