### PR TITLE
Feature/boolean param checkbox

### PR DESCRIPTION
**Pull request by neelbhanushali**
PR for issue #836 

* Currently checking if param type == `Boolean`. Have not made it case insensitive.
* I don't know how to write test for the package. Need someone to write them.
* Have used [Array.prototype.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) instead of [_.find](https://lodash.com/docs/#find) since `_.find` was throwing `_.find function not found` error in `send_sample_request.js`.
* Currently `trueValue` and `falseValue` are being sent as string even if `true` and `false` is set as `trueValue` and `falseValue`. Need help in this too.
* Might have created a lot of changes due to file formatting on save. If that is a problem, kindly let me know how do you guys format your files (html and js) while coding. I'll use the same plugin and update the PR.

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
See my comment on your PR on core. Mixing formatting/behavior changes isn't great (it's not the end of the world but it should be avoided as much as possible).

**Comment by neelbhanushali** [comment]
@NicolasCARPi I shall update that PR and this PR for formatting.

**Comment by neelbhanushali** [comment]
@NicolasCARPi I've updated the PR for formatting. Kindly have a look.

**Comment by neelbhanushali** [comment]
@NicolasCARPi @rottmann @manishsaraan Did you find time to review this PR?

**Comment by NicolasCARPi** [comment]
I tested your changes, but when trying to send a request, nothing would happen because: `ReferenceError: data is not defined`. On line 33 of `send_sample_request.js`.

**Pull request closed without merging**
