### PR TITLE
add support for api-data.json file output

### LINKED ISSUE #1043: apidoc didn't generate the docs anymore, white page
# Describe the bug

# Steps to reproduce
`apidoc -i src/ -o docs/`
The console didn't show anything, only the index.html and assets folder are generated. 

# Information

- Version of apidoc: latest version 0.50.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): MacOS
- Browser (e.g. firefox, chrome): Chrome

### LINKED ISSUE #1046: api_data.json and api_project.json no longer generated
# Describe the bug

The last version of apidoc (0.50.0) seems to not generate the JSON files anymore, which breaks the apidoc-markdown plugin (for example). I know this is more an issue for that project, but I don't see how they could fix it without those files. I tried searching through the commits to see where it was removed and [this](https://github.com/apidoc/apidoc/commit/aa05d6aa7416207572c170e29a6e3117dbeab0e6#diff-0d4a8db044ab1e69251470c5867c96087ba2629d39de216ab9d2a59c74afbff5) is the commit where it seems to have been removed. Judging by the commit description, it doesn't seem to be intentional. I didn't spend too much time on this, so I might be wrong. The bottom line is that those files were really useful and it would be a shame to remove them.
# Steps to reproduce

apidoc -i src -o ./apidoc

# Information

- Version of apidoc: v0.50.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): Manjaro
- Browser (e.g. firefox, chrome): Chrome

### LINKED ISSUE #1390: How can I generate api_data.json
How can I generate api_data.json so that I can import APIs to other tools. I noticed that the old version of apidoc could generate api_data.json, but the latest version removed this feature

### PR DESCRIPTION
**Pull request by gemal**
fixes #1043
fixes #1390
fixes #1046

Make sure to read [the contributing documentation](https://github.com/apidoc/apidoc/blob/master/CONTRIBUTING.md).

IMPORTANT: Base your PR off the 'dev' branch and target that branch for merging.

Would you accept a pull request like this? More work is needed but didn't want to do more if this was not an accepted way forward

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Hello,

Yes this can be interesting, but I would rather see a boolean flag, and the output is in the assets folder.

**Review by NicolasCARPi — CHANGES_REQUESTED** [review]
First, your code doesn't work because of capitalization bug of the option name in writer.js, but that's an easy fix.

Second, I would name the option: `--write-json` instead. The idea is to remove the terminology "data" which means nothing and is a word that should be avoided.

Finally, it would be important to explain better what it is. Maybe in the help add something like: this will create a file "parsed.json" with the parsed API info collected by the parser and used as source for the generation of the html.

Finally finally, add a test that at least verifies that with this option, a file is created.

**Review by NicolasCARPi — APPROVED** [review]

**Comment by NicolasCARPi** [comment]
Thank you for your contribution!

**Comment by gemal** [comment]
@NicolasCARPi thanks for good and fast guidance

**Comment by NicolasCARPi** [comment]
@gemal There are no schedule. If you want a release you'll need to make a PR that fixes a bug ;) (yeah, I'm blackmailing you!!)

**Comment by gemal** [comment]
I know that this was just a feature but still :)

**Comment by NicolasCARPi** [comment]
You added a feature, it is not a bugfix in my eyes, it was possible to get the data already, you just made it more convenient. Anyway, I'll make a release now.

**Pull request merged**
