### PR TITLE
Send sample request auto json body if body/json is not used but Content-Type application/json header is set

### PR DESCRIPTION
**Pull request by mparq**
Adding a PR to allow use of parameters as a json body if Content-Type: application/json header was given and the body/json field was not used.

I think this behavior used to exist after 0.18.0 but stopped existing after the body dropdown change in 0.19.0, but not too familiar with the code.

I also included ability to replace an optional url parameter, denoted by `:param?` '?' suffix with an empty string if parameter is not set. We make use of a lot of optional parameters like these

e.g. POST /page/:id? will create a new page if id is not defined but will update page of id if it is defined, and both are valid.

Edit:

I also included a fix for something I was running into, where by default, the parsed JSON for headers['Content-Type'] == 'application/json' as it is currently implemented will output all json values as strings e.g.

```
headers['Content-Type'] = 'application/json' // so we will try to auto-parse params into json body
params:
paramA: Boolean = true,
paramB: Number = 100

current json body:
{
    "paramA": "true",
    "paramB": "100"
}
```

New function `tryParsingWithTypes` will try to parse the json body output with the provided parameter type definition instead of leaving all values as string

```
new json body:
{
    "paramA": true,
    "paramB": 100
}
```

### CODE REVIEW

**Comment by mparq** [comment]
@NicolasCARPi let me know if this looks valid and merge-able, or if you have any feedback.

**Comment by NicolasCARPi** [comment]
Thank you for your contribution. I'll try and have a look (probably after friday where I have a big meeting to prepare for ;) ).

**Comment by NicolasCARPi** [comment]
Hello,

Could you please look into resolving the confilcts? :)

**Comment by mparq** [comment]
Sorry for the delay. Taking a look now.

**Comment by mparq** [comment]
Merged and resolved conflicts @NicolasCARPi. I also edited the OP to include info on extra code I added to parse the auto json body with parameter types instead of strings. Let me know if it makes sense!

**Comment by m0rt3nlund** [comment]
This would be great to get merged! :)

**Comment by NicolasCARPi** [comment]
Thanks @mparq

**Pull request merged**
