### PR TITLE
Sample requests with GET parameters need to be added to the query string

### PR DESCRIPTION
**Pull request by cosmincatalin**
@rottmann

### CODE REVIEW

**Comment by tielur** [comment]
:+1:

**Comment by 2naive** [comment]
@rottmann

**Comment by ramonvic** [comment]
It will not merged? I am with this same issue.

**Comment by phoenix741** [comment]
I have the same problem.

**Comment by alqu** [comment]
Huh? Still not merged?

Please merge this commit.

**Comment by rottmann** [comment]
Thanks, added in 0.14.0

**Comment by alqu** [comment]
yeah, thank you!

**Pull request closed without merging**
