### PR TITLE
Some practical changes   -dev

### PR DESCRIPTION
**Pull request by SxiaZB**
I initiated a new PR with only my latest changes

update record：
1、Added filtering navigation bar based on URL；
2、Add template setting parameter "aloneDisplay" to display one API or a group of APIs at a time。

### CODE REVIEW

**Comment by SxiaZB** [comment]
The above two commits are my changes

**Comment by NicolasCARPi** [comment]
Hello,

Thank you for your contribution. The filter is a nice addition.

Can you explain a bit more the "alone display" thing?

**Comment by SxiaZB** [comment]
With many APIs, it is difficult for me to focus on one API, because all APIs are displayed continuously.
"alone display" is that I can click the title on the nav to display the specific API. I set it like this now. Click the title of the API to display only the articles of this API. Click the title of the group to display a group of API articles .

**Comment by NicolasCARPi** [comment]
Ok I see. I'll add it to the doc. Thanks for the contribution! :)

**Pull request merged**
