### PR TITLE
add notes about elixir

### LINKED ISSUE #640: Elixir - Generates compile warnings on 1.4
Relevant Discussion:
https://github.com/rrrene/credo/issues/291

The use of module attributes was changed in elixir 1.4 to generate an error if it isn't used. The syntax should probably change a more traditional comment syntax like Go, Java, Java, etc to eliminate this warning.

### PR DESCRIPTION
**Pull request by techgaun**
closes #640 this requires https://github.com/apidoc/apidoc-core/pull/65 to be merged
it would also be great to have a new release if these get merged

### CODE REVIEW

**Comment by techgaun** [comment]
@rottmann sorry to bug you but any news on reviewing this?
On different note, I saw that you are looking for maintainers and I understand your busy time and thus I have to appreciate the effort you've put on apidoc project. I'm not a node/js expert but I could help manage and review pull requests and often fix bugs.

**Comment by novaugust** [comment]
Just a heads up since I'm using your branch - this doc is a little off. It won't pick it up if it's `# {` due to the space. 

```md
 * **Elixir**:

   ```elixir
   #{
   # This is a comment.
   #}
```

**Comment by techgaun** [comment]
sorry thanks @novaugust for the info. I updated the example.

**Comment by NicolasCARPi** [comment]
Cheers @techgaun :D

**Pull request merged**
