### PR TITLE
fix not checking the yarn folder (#1118)

### PR DESCRIPTION
**Pull request by 2hoyeong**
This PR is related to #1118
It seems to be working fine in my environment
Please any feedback

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Wouldn't a better approach use the pnpapi? https://yarnpkg.com/advanced/pnpapi

**Comment by 2hoyeong** [comment]
> Wouldn't a better approach use the pnpapi? https://yarnpkg.com/advanced/pnpapi

AFAIK. 

There is bootstrap.zip in yarn folder but Yarn disallow phantom dependency.

My project installed apidoc wouldn't contain a framework like bootstrap. So `pnpapi` cannot find bootstrap module.

```
error: Your application tried to access bootstrap, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
```

It could be because I don't know. If you know more about `pnpapi`, please tip.

**Comment by NicolasCARPi** [comment]
> My project installed apidoc wouldn't contain a framework like bootstrap

But apidoc requires it, so it would be installed in the dependencies of apidoc, not as a dependency of your project.

I'll look into this new yarn and pnp and see how it could be best implemented.

**Comment by 2hoyeong** [comment]
> But apidoc requires it, so it would be installed in the dependencies of apidoc, not as a dependency of your project.

I installed pnpapi in apidoc. 😂 But it works like that.

`pnpapi` package does not contain any code. So `require('pnpapi')` may have been loaded as `.pnp.cjs` in my project.

**Comment by NicolasCARPi** [comment]
While your approach might be valid, it isn't the best, so I'm going to close this PR. See https://github.com/apidoc/apidoc/issues/1118#issuecomment-1015454470

**Pull request closed without merging**
