### PR TITLE
Updates vendor libraries of the template.

### PR DESCRIPTION
**Pull request by heldersilva**
I've updated the base template to bootstrap version 3.3.6

I'm planing on doing the same to other components used on the base template (jQuery, Handlebars, etc.)

Tell me if you think this is a waste of time, or if it will bring some benefit to the project.

### CODE REVIEW

**Comment by rottmann** [comment]
On todo it is for a long time, but i did not find the time to update it. You are welcome to update the template.

**Comment by heldersilva** [comment]
I think we can call it "done". I'll update the template in another pull request, so it's easier to keep control of what is changed.

**Comment by heldersilva** [comment]
Can this changes be merged to the main code?

**Comment by rottmann** [comment]
Thanks! Huge update, i must review it and will merge it then.

**Comment by rottmann** [comment]
Thank you, after long time it will be merged in the next version.

**Pull request closed without merging**
