### PR TITLE
Handle nested fields when sending the request

### PR DESCRIPTION
**Pull request by omargho**
This PR intended to fix the issue #704 

Actually when user specify that as his params config 
```
@apiParam {Object} profile
@apiParam {String} profile.name 
@apiParam {Object} profile.birthday
@apiParam {Number} profile.birthday.year 
```
when it posts to the sampleUrl it will be sended as separated fields,
so with this modification fields will be nested into one object
```
profile: {
     name: "john"
     birthday: {
         year: "2222"
      }
}
```
if user don't specify the type of profile/birthday as `Object` or if he add a value to those filelds it will not be handled and it will sended as separated fields

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Hello,

Thank you very much for your contribution! Could you try and add some tests please?

**Comment by omargho** [comment]
Hello and Happy new year :tada:  :tada: , 
I added some tests

**Comment by NicolasCARPi** [comment]
Thanks @omargho. I'll try and review it soon!

**Comment by neelbhanushali** [comment]
@NicolasCARPi when will this pr be merged?

**Comment by NicolasCARPi** [comment]
@neelbhanushali When me or some other contributor with write access has the time and will to review it. Please keep in mind that this is free and open source software, so it is not reasonable to expect deadlines. That being said, I'm hoping to do it this week-end.

**Comment by neelbhanushali** [comment]
@NicolasCARPi I apologise if you felt rushed. I'm just excited to have replies (here and on gitter) from contributors that keep this package updated. I'm sorry again.

Can I help in any way?

**Comment by NicolasCARPi** [comment]
> Can I help in any way?

It's always possible for you to test the code and let us know if it works as expected and if you don't  see any glaring issue with it. The more reviewers, the better.

**Comment by neelbhanushali** [comment]
@NicolasCARPi I'm willing to help. Anything for #opensource 

But you'll have to let me know how to help you. 😅

**Comment by omargho** [comment]
@neelbhanushali you can review the code made in this PR or you can test it by cloning my repo and use it to create the docs for your projects and tell us if everything works well or if there is some issues

**Comment by NicolasCARPi** [comment]
Shouldn't the params of type object be hidden from the form? So in your example, profile and profile.birthday should not appear as input, don't you think?

**Comment by neelbhanushali** [comment]
@NicolasCARPi same comment from my side

**Comment by omargho** [comment]
@NicolasCARPi you mean the generated form ? if it's the case i think it should appear as input in case of user wants to pass a valid JSON object

**Comment by neelbhanushali** [comment]
@omargho Valid point.

But in current case, there is a great possibility that `year` will be accessed as `$_REQUEST['profile']['birthday']['year']` (for php) on backend side and passing JSON in the key `birthday` or passing JSON in key `profile` will throw an error since at server side JSON will be treated as string. And which is why @NicolasCARPi is suggesting that the params of type `Object` namely `profile` and `birthday` should be hidden.

Since filling those inputs disrupts the nested structure that was supposed to be sent as input.

**Comment by omargho** [comment]
i can handle the parsing in case of those input where filled with a valid JSON objects.
what do u think ?

**Comment by neelbhanushali** [comment]
@omargho that sounds like a good plan.
@NicolasCARPi what do you think?

**Comment by NicolasCARPi** [comment]
I would go with hiding the input field if the type is object.

**Comment by omargho** [comment]
if user specify only Object type params , all inputs will be hidden ? 
Does the `param` and  `paramType` objects in `sendSampleRequest` function will contain the hidden param (if it's not the case the changes of this PR will be broken)
i think if hiding the params is already in the roadmap , it should be implemented before handling the nested fields.

**Comment by NicolasCARPi** [comment]
Alternatively, we can merge this as it is and think about a better way to handle objects/arrays inputs later..

**Comment by neelbhanushali** [comment]
@NicolasCARPi have you released a new version of the package?

**Comment by NicolasCARPi** [comment]
@neelbhanushali not yet no. There are still some things to do before doing that, but it's coming soon.

**Pull request merged**
