### PR TITLE
Remove extra documentation example which causes example to fail

### PR DESCRIPTION
**Pull request by SWheeler17**
In the `/example` folder, there were two files with similiar ApiDoc data. The two file seemed to make the example documentation partially break. This PR removes one of the extra files.

### CODE REVIEW

**Comment by SWheeler17** [comment]
The build is complaining about `@apiUse`. Not sure if that is expected.

**Comment by NicolasCARPi** [comment]
I'm not sure that's a valid approach, as the `_apidoc.js` file is here to document older versions and din't cause issues before. It also defines the CreateUserError, so this is why it complains with the apiuse afterwards.

**Comment by SWheeler17** [comment]
So should I update the new documentation instead of deleting the old one? The reason it seemed to break (if I remember correctly) was that the old documentation `_apidoc.js` had some of the same names as the new documentation `example.js`.

**Comment by NicolasCARPi** [comment]
But what issue precisely are you trying to fix? Because for me the doc compiles fine with a fresh apidoc clone.

**Comment by SWheeler17** [comment]
The doc compiles for me as well, but if I access the documentation from a browser the highlighting (and the gray bars) on the left sidebar is/are not correct/accurate.
Screen Shot 2021-07-14 at 16 27 52

**Comment by NicolasCARPi** [comment]
Works fine for me!

**Pull request closed without merging**
